### PR TITLE
major refactoring -> ver 2.0

### PR DESCRIPTION
**Pull request by tdjastrzebski**
Hi,

this is a major refactoring and code improvement I did trying to enhance this solution so it meets demands.
Main functional improvements:
1. Database has been optimized, performance improved. No changes to existing database field names, existing reports should continue to work.
2. Additional tables for record tags and additional info added. 
3. WebJobUsageDaily no longer requires external trigger, run schedule is defined in app.config and works based on TimerTriggerAttribute - Microsoft.Azure.WebJobs.Extensions package.
4. SqlBulkCopy used to load records much faster.

Minor changes:
Inconsistent product name fixed (Azure Usage and Billing Insights - AUBI)

BR,
Tomasz Jastrzębski

### CODE REVIEW

**Comment by mustafakasap** [comment]
Thanks @tdjastrzebski may you give a bit more detail on item 3? I am testing your pull request end to end. It seems we can remove the webjobs from the project.

**Comment by tdjastrzebski** [comment]
Hello Mustafa,

 

How would you like to replace WebJobs?

The solution needs some kind of process/agent running on schedule.

 

I modified #3 description a bit. Actually, only WebJobUsageDaily needs to be scheduled. Trigger is implemented based on TimerTriggerAttribute found in Microsoft.Azure.WebJobs.Extensions package.

 

Best regards,

 

Tomasz Jastrzębski

**Comment by mustafakasap** [comment]
Hi Thomasz, I will merge this pull request but noticed Apache license added on the headers of some files. To be able to approve them, all files must be under MIT license. May you change them to MIT?

Thanks,

**Comment by tdjastrzebski** [comment]
Hi Mustafa,
I found Apache license within: AdalTokenCache, DataAccess and ReportRequest files.
This license was there in the original version. I assume Microsoft Corporation has rights and Apache license was used mistakenly instead of MIT license. Please let me know it this is not the case so we do not violate someone's rights. I made the requested change.
BR,
Tomasz

**Comment by mustafakasap** [comment]
Thanks Thomasz, I will keep the original files as is with their Apache licenses. I thought there were additional ones from you. I will review all and will commit asap.

**Comment by tdjastrzebski** [comment]
Mustafa, meanwhile I added AzureUsageRecordsView DB view.
As far as licenses: note that existing Apache licenses were incomplete - they did not include license owner.

**Pull request merged**
